name: Test .NET MAUI Android App

on:
  workflow_dispatch:
  
env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
  MAUI_CSPROJ_TO_BUILD: MauiUITestSample/MauiUITestSample.csproj
  UITEST_CSPROJ_TO_BUILD: MyAppTests/MyAppTests.csproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build .NET MAUI App
      run: dotnet publish ${{ env.MAUI_CSPROJ_TO_BUILD }} -c ${{ env.BUILD_CONFIGURATION }} -f net7.0-android -o ${{ github.workspace }}\\artifacts
      
    - name: Build UITest Project
      run: dotnet build ${{ env.UITEST_CSPROJ_TO_BUILD }} -c ${{ env.BUILD_CONFIGURATION }}
      
    - name: Install App Center CLI
      run: npm install --location=global appcenter-cli
      
    - name: Upload App to Test Cloud
      run: "appcenter test run uitest --app \"xtc-Xamarin-Forms/MauiTest\" --devices ff8f571c --app-path \"${{ github.workspace }}\\artifacts\\com.companyname.mauiuitestsample-Signed.apk\" --test-series \"master\" --locale \"en_US\" --build-dir \"MyAppTests/bin/${{ env.BUILD_CONFIGURATION }}/net48/\" --uitest-tools-dir \"MyAppTests/bin/${{ env.BUILD_CONFIGURATION }}/net48/\" --token \"${{ secrets.APPCENTER_TOKEN_ANDROID }}\""
