name: Test .NET MAUI iOS App

on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
  MAUI_CSPROJ_TO_BUILD: MauiUITestSample/MauiUITestSample.csproj
  UITEST_CSPROJ_TO_BUILD: MyAppTests/MyAppTests.csproj

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui
    
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.P12_FILE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.companyname.mauiuitestsample'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish .NET MAUI iOS App
      run: dotnet publish ${{ env.MAUI_CSPROJ_TO_BUILD }} -c ${{ env.BUILD_CONFIGURATION }} -f net7.0-ios -o ${{ github.workspace }}/artifacts/
      
    - name: Build UITest Project
      run: dotnet build ${{ env.UITEST_CSPROJ_TO_BUILD }} -c ${{ env.BUILD_CONFIGURATION }}
      
    - name: Install App Center CLI
      run: npm install --location=global appcenter-cli
      
    - name: Upload App to Test Cloud
      run: "appcenter test run uitest --app \"xtc-Xamarin-Forms/MauiTest-iOS\" --devices 1f1515d2 --app-path \"${{ github.workspace }}/artifacts/MauiUITestSample.ipa\" --test-series \"master\" --locale \"en_US\" --build-dir \"MyAppTests/bin/${{ env.BUILD_CONFIGURATION }}/net48/\" --uitest-tools-dir \"MyAppTests/bin/${{ env.BUILD_CONFIGURATION }}/net48/\" --token \"${{ secrets.APPCENTER_TOKEN_IOS }}\" --async"
